kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "elastifile"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
