FROM gcr.io/google-appengine/debian9

RUN apt-get update && apt-get install -y --no-install-recommends less vim screen iputils-ping ssh-client iproute2 curl nfs-common tcpdump tshark telnet

CMD tail -f /dev/null

