FROM gcr.io/google-appengine/debian9

RUN apt-get update && apt-get install -y --no-install-recommends less vim screen iputils-ping ssh-client iproute2 curl nfs-common tcpdump tshark telnet procps

#CMD time dd if=/dev/urandom of=/mnt/test/testfile bs=4k count=1000
#CMD tail -f /dev/null
