application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  imageProvisioner:
    type: string
    default: $REGISTRY/provisioner:$TAG
    x-google-marketplace:
      type: IMAGE
  imageCustomScript:
    type: string
    default: $REGISTRY/provisioner/custom_script:$TAG
    x-google-marketplace:
      type: IMAGE
  emanageAddress:
    title: Elastifile Management Console URL
    description: URL for access to the Elastifile management console (should start with https://)
    type: string
    maxLength: 128
    default: 'https://elastifile-management.example.com'
  nfsAddress:
    title: NFS Address
    description: DNS name / IP address for storage access
    type: string
    maxLength: 128
  emanageUser:
    title: Username
    description: Username for logging into the Elastifile management console
    type: string
    default: 'admin'
    maxLength: 64
  emanagePassword:
    title: Password
    description: Password for logging into the Elastifile management console
    type: string
    maxLength: 64
    default: 'changeme'
  serviceAccount:
    type: string
    default: elastifile-provisioner-sa
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
            - apiGroups: [""]
              resources: ["persistentvolumes"]
              verbs: ["get", "list", "watch", "create", "delete"]
            - apiGroups: [""]
              resources: ["persistentvolumeclaims"]
              verbs: ["get", "list", "watch", "update"]
            - apiGroups: ["storage.k8s.io"]
              resources: ["storageclasses"]
              verbs: ["*"]
            - apiGroups: [""]
              resources: ["events"]
              verbs: ["list", "watch", "create", "update", "patch"]
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["get", "list", "watch", "create", "delete"]
            - apiGroups: ["app.k8s.io"]
              resources: ["applications"] # Required for garbage collection
              verbs: ["get", "list", "watch"]
required:
- name
- namespace
- imageProvisioner
- imageCustomScript
- emanageAddress
- nfsAddress
- emanageUser
- emanagePassword
