kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: elastifile
provisioner: elastifile.com/nfs
parameters:
  nfsServer: "nfsaddr"
  restURL: "https://managementaddr"
  username: "admin"
  secretName: "elastifile-rest"
  secretNamespace: "default"
