kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: elastifile-provisioner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elastifile-provisioner
    spec:
      containers:
        - name: elastifile-provisioner
          image: quay.io/elastifile/elastifile-provisioner
          imagePullPolicy: Always
